-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.access_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  system_key text UNIQUE,
  name text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  permission_codes ARRAY NOT NULL DEFAULT '{}'::text[] CHECK (cardinality(permission_codes) > 0),
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT access_roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.appointment_additional_doctors (
  appointment_id uuid NOT NULL,
  doctor_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT appointment_additional_doctors_pkey PRIMARY KEY (appointment_id, doctor_id),
  CONSTRAINT appt_add_doctors_appointment_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT appt_add_doctors_doctor_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(id)
);
CREATE TABLE public.appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid,
  doctor_id uuid,
  specialty_id uuid,
  service_id uuid,
  booking_id uuid,
  scheduled_at timestamp with time zone NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'scheduled'::appointment_status,
  source text NOT NULL DEFAULT 'internal'::text,
  reason text NOT NULL DEFAULT ''::text,
  notes text NOT NULL DEFAULT ''::text,
  visit_type text NOT NULL DEFAULT 'in_person'::text CHECK (visit_type = ANY (ARRAY['in_person'::text, 'teleconsultation'::text])),
  teleconsultation_platform text,
  teleconsultation_url text,
  teleconsultation_access_instructions text,
  teleconsultation_provider text CHECK (teleconsultation_provider = 'jitsi'::text OR teleconsultation_provider IS NULL),
  teleconsultation_room_name text,
  consultation_id uuid,
  completed_by uuid,
  completed_at timestamp with time zone,
  related_referral_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  additional_doctor_ids ARRAY DEFAULT '{}'::uuid[],
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT appointments_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(id),
  CONSTRAINT appointments_specialty_id_fkey FOREIGN KEY (specialty_id) REFERENCES public.specialties(id),
  CONSTRAINT appointments_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT appointments_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT appointments_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.profiles(id),
  CONSTRAINT appointments_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  actor_id uuid,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id uuid,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  service_id uuid NOT NULL,
  doctor_id uuid,
  preferred_date date NOT NULL,
  preferred_time time without time zone NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::booking_status,
  intake_notes text NOT NULL DEFAULT ''::text,
  fee_type text NOT NULL DEFAULT 'consultation'::text CHECK (fee_type = ANY (ARRAY['consultation'::text, 'follow_up'::text])),
  fee_amount numeric NOT NULL DEFAULT 0,
  receipt_code text UNIQUE,
  payment_status text NOT NULL DEFAULT 'pending_cashier'::text CHECK (payment_status = ANY (ARRAY['pending_cashier'::text, 'paid'::text])),
  appointment_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  promo_code_id uuid,
  discount_amount numeric NOT NULL DEFAULT 0,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT bookings_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.services(id),
  CONSTRAINT bookings_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(id),
  CONSTRAINT bookings_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT bookings_promo_code_id_fkey FOREIGN KEY (promo_code_id) REFERENCES public.promo_codes(id)
);
CREATE TABLE public.chat_threads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  participant_a uuid NOT NULL,
  participant_b uuid NOT NULL,
  thread_key text NOT NULL UNIQUE,
  type text NOT NULL DEFAULT 'direct'::text,
  linked_appointment_id uuid,
  linked_referral_id uuid,
  last_message_text text,
  last_message_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT chat_threads_pkey PRIMARY KEY (id),
  CONSTRAINT chat_threads_participant_a_fkey FOREIGN KEY (participant_a) REFERENCES public.profiles(id),
  CONSTRAINT chat_threads_participant_b_fkey FOREIGN KEY (participant_b) REFERENCES public.profiles(id),
  CONSTRAINT chat_threads_linked_appointment_id_fkey FOREIGN KEY (linked_appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT chat_threads_linked_referral_id_fkey FOREIGN KEY (linked_referral_id) REFERENCES public.referrals(id)
);
CREATE TABLE public.clinic_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_name text NOT NULL,
  legal_name text NOT NULL,
  short_code text NOT NULL UNIQUE,
  address text NOT NULL,
  contact_number text NOT NULL,
  email text NOT NULL,
  website text NOT NULL,
  logo_url text,
  primary_color text NOT NULL DEFAULT '#155eef'::text,
  accent_color text NOT NULL DEFAULT '#0f766e'::text,
  booking_lead_days integer NOT NULL DEFAULT 30,
  booking_cancellation_hours integer NOT NULL DEFAULT 12,
  appointment_slot_minutes integer NOT NULL DEFAULT 30,
  operating_hours jsonb NOT NULL DEFAULT '[]'::jsonb,
  system_enabled boolean NOT NULL DEFAULT true,
  system_message text NOT NULL DEFAULT 'Contact your System Administrator to continue using the System'::text,
  odc_recovery_password_hash text,
  enabled_modules jsonb NOT NULL DEFAULT '{"pos": true, "billing": true, "dashboard": true, "inventory": true, "laboratory": true, "teleconsult": true, "patient_management": true, "booking_appointments": true}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  system_status_type text DEFAULT 'maintenance'::text,
  CONSTRAINT clinic_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.clinics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT clinics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.consultation_soap_notes_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL,
  appointment_id uuid,
  patient_id uuid NOT NULL,
  doctor_id uuid NOT NULL,
  change_type text NOT NULL CHECK (change_type = ANY (ARRAY['insert'::text, 'update'::text])),
  changed_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  old_snapshot jsonb,
  new_snapshot jsonb NOT NULL,
  CONSTRAINT consultation_soap_notes_history_pkey PRIMARY KEY (id),
  CONSTRAINT consultation_soap_notes_history_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.consultation_types (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT consultation_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.consultations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  appointment_id uuid UNIQUE,
  patient_id uuid NOT NULL,
  doctor_id uuid NOT NULL,
  subjective text NOT NULL DEFAULT ''::text,
  objective text NOT NULL DEFAULT ''::text,
  assessment text NOT NULL DEFAULT ''::text,
  plan text NOT NULL DEFAULT ''::text,
  outcome text NOT NULL DEFAULT ''::text,
  consultation_type text,
  consultation_date date,
  consultation_time time without time zone,
  provider_name text,
  clinical_summary text,
  diagnosis text,
  present_illness_history text,
  review_of_symptoms text,
  allergies text,
  vitals text,
  treatment_plan text,
  medications text,
  lab_results text,
  differential_diagnosis text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT consultations_pkey PRIMARY KEY (id),
  CONSTRAINT consultations_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT consultations_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT consultations_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(id)
);
CREATE TABLE public.doctor_availability (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  doctor_id uuid NOT NULL,
  day_of_week integer NOT NULL CHECK (day_of_week >= 0 AND day_of_week <= 6),
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  slot_minutes integer NOT NULL DEFAULT 30,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT doctor_availability_pkey PRIMARY KEY (id),
  CONSTRAINT doctor_availability_doctor_id_fkey FOREIGN KEY (doctor_id) REFERENCES public.doctors(id)
);
CREATE TABLE public.doctors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  license_number text,
  specialty_id uuid,
  license_expiry date,
  bir_number text,
  prc_id_path text,
  consultation_fee numeric NOT NULL DEFAULT 0,
  follow_up_fee numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  ptr_number text,
  CONSTRAINT doctors_pkey PRIMARY KEY (id),
  CONSTRAINT doctors_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT doctors_specialty_id_fkey FOREIGN KEY (specialty_id) REFERENCES public.specialties(id)
);
CREATE TABLE public.file_uploads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  file_name text NOT NULL,
  category text NOT NULL,
  storage_bucket text NOT NULL DEFAULT 'patient-files'::text,
  storage_path text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT file_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT file_uploads_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.hmo_authorizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  appointment_id uuid,
  hmo_provider_id uuid NOT NULL,
  authorization_code text,
  coverage_amount numeric DEFAULT 0,
  approval_status text NOT NULL DEFAULT 'pending'::text,
  approved_by text,
  approval_date timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hmo_authorizations_pkey PRIMARY KEY (id),
  CONSTRAINT hmo_authorizations_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT hmo_authorizations_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT hmo_authorizations_hmo_provider_id_fkey FOREIGN KEY (hmo_provider_id) REFERENCES public.hmo_providers(id)
);
CREATE TABLE public.hmo_claim_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  service_name text NOT NULL,
  doctor_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  amount numeric NOT NULL DEFAULT 0,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hmo_claim_items_pkey PRIMARY KEY (id),
  CONSTRAINT hmo_claim_items_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.hmo_claims(id)
);
CREATE TABLE public.hmo_claims (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  authorization_id uuid,
  invoice_number text,
  total_amount numeric DEFAULT 0,
  covered_amount numeric DEFAULT 0,
  patient_excess numeric DEFAULT 0,
  claim_status text NOT NULL DEFAULT 'draft'::text,
  submission_date timestamp with time zone,
  payment_due_date timestamp with time zone,
  paid_date timestamp with time zone,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  patient_id uuid,
  CONSTRAINT hmo_claims_pkey PRIMARY KEY (id),
  CONSTRAINT hmo_claims_authorization_id_fkey FOREIGN KEY (authorization_id) REFERENCES public.hmo_authorizations(id),
  CONSTRAINT hmo_claims_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.hmo_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  claim_id uuid NOT NULL,
  payment_reference text,
  amount_paid numeric NOT NULL DEFAULT 0,
  payment_date timestamp with time zone NOT NULL DEFAULT now(),
  payment_method text DEFAULT 'bank_transfer'::text,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hmo_payments_pkey PRIMARY KEY (id),
  CONSTRAINT hmo_payments_claim_id_fkey FOREIGN KEY (claim_id) REFERENCES public.hmo_claims(id)
);
CREATE TABLE public.hmo_providers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  code text,
  contact_person text,
  contact_email text,
  contact_number text,
  address text,
  submission_cycle text DEFAULT 'monthly'::text,
  payment_terms_days integer DEFAULT 30,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT hmo_providers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT inventory_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  supplier_id uuid,
  name text NOT NULL,
  sku text NOT NULL UNIQUE,
  unit text NOT NULL,
  stock_on_hand integer NOT NULL DEFAULT 0,
  reorder_level integer NOT NULL DEFAULT 0,
  qr_code text NOT NULL,
  cost_price numeric NOT NULL DEFAULT 0 CHECK (cost_price >= 0::numeric),
  selling_price numeric NOT NULL DEFAULT 0 CHECK (selling_price >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  CONSTRAINT inventory_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.inventory_categories(id),
  CONSTRAINT inventory_items_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.suppliers(id)
);
CREATE TABLE public.inventory_usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  appointment_id uuid,
  item_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  notes text NOT NULL DEFAULT ''::text,
  scanned_code text NOT NULL,
  recorded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT inventory_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_usage_logs_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT inventory_usage_logs_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT inventory_usage_logs_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.inventory_items(id),
  CONSTRAINT inventory_usage_logs_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  description text NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  unit_price numeric NOT NULL DEFAULT 0,
  category text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  reference_id text,
  reference_type text,
  CONSTRAINT invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  appointment_id uuid,
  invoice_number text NOT NULL UNIQUE,
  payment_status USER-DEFINED NOT NULL DEFAULT 'unpaid'::payment_status,
  service_request_id uuid,
  subtotal numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  discount_type text DEFAULT 'none'::text,
  discount_amount numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT invoices_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id)
);
CREATE TABLE public.lab_accession_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_request_id uuid NOT NULL UNIQUE,
  accession_number text NOT NULL UNIQUE,
  specimen_type text NOT NULL DEFAULT ''::text,
  specimen_collected_at timestamp with time zone,
  specimen_received_at timestamp with time zone,
  specimen_condition text NOT NULL DEFAULT 'adequate'::text,
  collected_by uuid,
  accessioned_by uuid,
  notes text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT lab_accession_log_pkey PRIMARY KEY (id),
  CONSTRAINT lab_accession_log_service_request_id_fkey FOREIGN KEY (service_request_id) REFERENCES public.service_requests(id),
  CONSTRAINT lab_accession_log_collected_by_fkey FOREIGN KEY (collected_by) REFERENCES public.profiles(id),
  CONSTRAINT lab_accession_log_accessioned_by_fkey FOREIGN KEY (accessioned_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.lab_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_request_id uuid NOT NULL,
  action text NOT NULL,
  old_value text,
  new_value text,
  performed_by uuid NOT NULL,
  performed_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT lab_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT lab_audit_log_service_request_id_fkey FOREIGN KEY (service_request_id) REFERENCES public.service_requests(id),
  CONSTRAINT lab_audit_log_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.lab_reagent_links (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  medical_service_id uuid NOT NULL,
  inventory_item_id uuid NOT NULL,
  quantity_per_test numeric NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT lab_reagent_links_pkey PRIMARY KEY (id),
  CONSTRAINT lab_reagent_links_medical_service_id_fkey FOREIGN KEY (medical_service_id) REFERENCES public.medical_services(id),
  CONSTRAINT lab_reagent_links_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.inventory_items(id)
);
CREATE TABLE public.lab_request_documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  consultation_id uuid,
  requested_by uuid,
  target_laboratory text NOT NULL DEFAULT ''::text,
  requested_tests text NOT NULL DEFAULT ''::text,
  clinical_notes text NOT NULL DEFAULT ''::text,
  document_html text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT lab_request_documents_pkey PRIMARY KEY (id),
  CONSTRAINT lab_request_documents_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT lab_request_documents_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT lab_request_documents_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.lab_result_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_request_id uuid NOT NULL,
  parameter_id uuid NOT NULL,
  value_numeric numeric,
  value_text text,
  abnormal_flag text NOT NULL DEFAULT 'normal'::text CHECK (abnormal_flag = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'critical'::text])),
  entered_by uuid NOT NULL,
  entered_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT lab_result_entries_pkey PRIMARY KEY (id),
  CONSTRAINT lab_result_entries_service_request_id_fkey FOREIGN KEY (service_request_id) REFERENCES public.service_requests(id),
  CONSTRAINT lab_result_entries_parameter_id_fkey FOREIGN KEY (parameter_id) REFERENCES public.lab_test_parameters(id),
  CONSTRAINT lab_result_entries_entered_by_fkey FOREIGN KEY (entered_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.lab_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  price numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT lab_services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lab_test_panel_services (
  panel_id uuid NOT NULL,
  medical_service_id uuid NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT lab_test_panel_services_pkey PRIMARY KEY (panel_id, medical_service_id),
  CONSTRAINT lab_panel_services_panel_fkey FOREIGN KEY (panel_id) REFERENCES public.lab_test_panels(id),
  CONSTRAINT lab_panel_services_service_fkey FOREIGN KEY (medical_service_id) REFERENCES public.medical_services(id)
);
CREATE TABLE public.lab_test_panels (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  medical_service_ids ARRAY NOT NULL DEFAULT '{}'::uuid[],
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT lab_test_panels_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lab_test_parameters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  medical_service_id uuid NOT NULL,
  parameter_name text NOT NULL,
  unit text NOT NULL DEFAULT ''::text,
  data_type text NOT NULL DEFAULT 'numeric'::text CHECK (data_type = ANY (ARRAY['numeric'::text, 'text'::text, 'select'::text])),
  sort_order integer NOT NULL DEFAULT 0,
  reference_range_male_low numeric,
  reference_range_male_high numeric,
  reference_range_female_low numeric,
  reference_range_female_high numeric,
  reference_range_child_low numeric,
  reference_range_child_high numeric,
  reference_range_general_low numeric,
  reference_range_general_high numeric,
  select_options jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT lab_test_parameters_pkey PRIMARY KEY (id),
  CONSTRAINT lab_test_parameters_medical_service_id_fkey FOREIGN KEY (medical_service_id) REFERENCES public.medical_services(id)
);
CREATE TABLE public.medical_certificates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  certificate_purpose text NOT NULL DEFAULT ''::text,
  diagnosis text NOT NULL DEFAULT ''::text,
  recommendation text NOT NULL DEFAULT ''::text,
  rest_from date,
  rest_until date,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT medical_certificates_pkey PRIMARY KEY (id),
  CONSTRAINT medical_certificates_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT medical_certificates_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.medical_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid,
  department text NOT NULL,
  category text NOT NULL,
  name text NOT NULL,
  description text,
  service_fee numeric NOT NULL DEFAULT 0,
  estimated_duration_minutes integer,
  priority text NOT NULL DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT medical_services_pkey PRIMARY KEY (id),
  CONSTRAINT medical_services_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.medical_services_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid UNIQUE,
  appointment_id uuid,
  patient_id uuid NOT NULL,
  provider_id uuid,
  consultation_type text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  actor uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT medical_services_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT medical_services_transactions_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT medical_services_transactions_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT medical_services_transactions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT medical_services_transactions_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.doctors(id),
  CONSTRAINT medical_services_transactions_actor_fkey FOREIGN KEY (actor) REFERENCES public.profiles(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  thread_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  text text NOT NULL,
  sent_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.chat_threads(id),
  CONSTRAINT messages_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.patient_hmo_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  hmo_provider_id uuid NOT NULL,
  card_number text,
  member_type text DEFAULT 'principal'::text,
  principal_name text,
  expiration_date date,
  coverage_limit numeric DEFAULT 0,
  remaining_balance numeric DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT patient_hmo_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT patient_hmo_accounts_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT patient_hmo_accounts_hmo_provider_id_fkey FOREIGN KEY (hmo_provider_id) REFERENCES public.hmo_providers(id)
);
CREATE TABLE public.patient_medical_history_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  consultation_id uuid,
  appointment_id uuid,
  provider_id uuid,
  history_text text NOT NULL DEFAULT ''::text,
  findings_text text NOT NULL DEFAULT ''::text,
  diagnoses_text text NOT NULL DEFAULT ''::text,
  treatment_summary_text text NOT NULL DEFAULT ''::text,
  soap_notes_text text NOT NULL DEFAULT ''::text,
  supplementary_docs_text text NOT NULL DEFAULT ''::text,
  actor uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT patient_medical_history_entries_pkey PRIMARY KEY (id),
  CONSTRAINT patient_medical_history_entries_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT patient_medical_history_entries_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT patient_medical_history_entries_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT patient_medical_history_entries_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.doctors(id),
  CONSTRAINT patient_medical_history_entries_actor_fkey FOREIGN KEY (actor) REFERENCES public.profiles(id)
);
CREATE TABLE public.patient_vitals_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  appointment_id uuid,
  consultation_id uuid,
  recorded_by uuid,
  temperature text,
  blood_pressure text,
  heart_rate text,
  respiratory_rate text,
  o2_sat text,
  weight text,
  height text,
  recorded_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT patient_vitals_history_pkey PRIMARY KEY (id),
  CONSTRAINT patient_vitals_history_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT patient_vitals_history_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT patient_vitals_history_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT patient_vitals_history_recorded_by_fkey FOREIGN KEY (recorded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.patients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  first_name text NOT NULL,
  last_name text NOT NULL,
  sex text NOT NULL,
  birth_date date NOT NULL,
  mobile_number text,
  email text,
  address text,
  blood_type text,
  allergies text NOT NULL DEFAULT ''::text,
  medical_history text NOT NULL DEFAULT ''::text,
  emergency_contact_name text,
  emergency_contact_phone text,
  qr_code text NOT NULL,
  intake_source text NOT NULL DEFAULT 'online_registration'::text CHECK (intake_source = ANY (ARRAY['online_registration'::text, 'staff_walk_in'::text])),
  visit_status text NOT NULL DEFAULT 'registered_no_visit'::text CHECK (visit_status = ANY (ARRAY['registered_no_visit'::text, 'visited_clinic'::text])),
  last_clinic_visit_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  temperature text,
  blood_pressure text,
  heart_rate text,
  respiratory_rate text,
  weight text,
  height text,
  vitals_recorded_at timestamp with time zone,
  o2_sat text,
  unique_login_id text,
  walk_in_account_claimed_at timestamp with time zone,
  CONSTRAINT patients_pkey PRIMARY KEY (id),
  CONSTRAINT patients_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid NOT NULL,
  amount numeric NOT NULL,
  method text NOT NULL,
  reference_number text,
  received_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT payments_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pos_sale_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL,
  inventory_item_id uuid NOT NULL,
  item_name text NOT NULL,
  item_sku text NOT NULL,
  item_unit text NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  unit_price numeric NOT NULL CHECK (unit_price >= 0::numeric),
  line_total numeric NOT NULL CHECK (line_total >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT pos_sale_items_pkey PRIMARY KEY (id),
  CONSTRAINT pos_sale_items_sale_id_fkey FOREIGN KEY (sale_id) REFERENCES public.pos_sales(id),
  CONSTRAINT pos_sale_items_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES public.inventory_items(id)
);
CREATE TABLE public.pos_sales (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  sale_number text NOT NULL UNIQUE,
  patient_id uuid,
  cashier_id uuid NOT NULL,
  payment_method text NOT NULL CHECK (payment_method = ANY (ARRAY['cash'::text, 'gcash'::text, 'card'::text])),
  payment_reference text,
  payment_notes text,
  subtotal numeric NOT NULL DEFAULT 0 CHECK (subtotal >= 0::numeric),
  total numeric NOT NULL DEFAULT 0 CHECK (total >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT pos_sales_pkey PRIMARY KEY (id),
  CONSTRAINT pos_sales_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT pos_sales_cashier_id_fkey FOREIGN KEY (cashier_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.prescriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  consultation_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  medication text NOT NULL,
  dosage text NOT NULL,
  instructions text NOT NULL,
  prescription_name text,
  instruction text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT prescriptions_pkey PRIMARY KEY (id),
  CONSTRAINT prescriptions_consultation_id_fkey FOREIGN KEY (consultation_id) REFERENCES public.consultations(id),
  CONSTRAINT prescriptions_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.profile_access_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  access_role_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT profile_access_roles_pkey PRIMARY KEY (id),
  CONSTRAINT profile_access_roles_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id),
  CONSTRAINT profile_access_roles_access_role_id_fkey FOREIGN KEY (access_role_id) REFERENCES public.access_roles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'patient'::app_role,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  phone text,
  title text,
  clinic_id uuid,
  department text,
  first_name text,
  last_name text,
  is_active boolean NOT NULL DEFAULT true,
  security_pin_hash text,
  pin_updated_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id)
);
CREATE TABLE public.promo_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  description text NOT NULL DEFAULT ''::text,
  max_uses integer NOT NULL DEFAULT 10 CHECK (max_uses >= 1),
  used_count integer NOT NULL DEFAULT 0 CHECK (used_count >= 0),
  discount_type text NOT NULL DEFAULT 'percentage'::text CHECK (discount_type = ANY (ARRAY['percentage'::text, 'fixed'::text, 'free'::text])),
  discount_value numeric NOT NULL DEFAULT 0 CHECK (discount_value >= 0::numeric),
  applicable_service_id uuid,
  active boolean NOT NULL DEFAULT true,
  expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  CONSTRAINT promo_codes_pkey PRIMARY KEY (id),
  CONSTRAINT promo_codes_applicable_service_id_fkey FOREIGN KEY (applicable_service_id) REFERENCES public.services(id)
);
CREATE TABLE public.referrals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  patient_id uuid NOT NULL,
  appointment_id uuid,
  referring_doctor_id uuid NOT NULL,
  target_doctor_id uuid,
  target_specialty_id uuid,
  reason text NOT NULL DEFAULT ''::text,
  clinical_summary text NOT NULL DEFAULT ''::text,
  referral_notes text NOT NULL DEFAULT ''::text,
  status text NOT NULL DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['draft'::text, 'sent'::text, 'pending'::text, 'accepted'::text, 'confirmed'::text, 'completed'::text, 'declined'::text, 'cancelled'::text])),
  specialist_findings text NOT NULL DEFAULT ''::text,
  specialist_recommendations text NOT NULL DEFAULT ''::text,
  referred_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  specialist_visited_at timestamp with time zone,
  completed_at timestamp with time zone,
  source_appointment_id uuid,
  source_consultation_id uuid,
  appointment_date date,
  appointment_time time without time zone,
  generalist_notes text NOT NULL DEFAULT ''::text,
  practice_location jsonb NOT NULL DEFAULT '{}'::jsonb,
  specialist_schedule_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  CONSTRAINT referrals_pkey PRIMARY KEY (id),
  CONSTRAINT referrals_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id),
  CONSTRAINT referrals_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT referrals_referring_doctor_id_fkey FOREIGN KEY (referring_doctor_id) REFERENCES public.doctors(id),
  CONSTRAINT referrals_target_doctor_id_fkey FOREIGN KEY (target_doctor_id) REFERENCES public.doctors(id),
  CONSTRAINT referrals_target_specialty_id_fkey FOREIGN KEY (target_specialty_id) REFERENCES public.specialties(id),
  CONSTRAINT referrals_source_appointment_id_fkey FOREIGN KEY (source_appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT referrals_source_consultation_id_fkey FOREIGN KEY (source_consultation_id) REFERENCES public.consultations(id)
);
CREATE TABLE public.service_request_media (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_request_id uuid NOT NULL,
  file_path text NOT NULL,
  mime_type text,
  uploaded_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT service_request_media_pkey PRIMARY KEY (id),
  CONSTRAINT service_request_media_service_request_id_fkey FOREIGN KEY (service_request_id) REFERENCES public.service_requests(id),
  CONSTRAINT service_request_media_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.service_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  clinic_id uuid NOT NULL,
  patient_id uuid NOT NULL,
  requested_by uuid NOT NULL,
  department text NOT NULL DEFAULT 'Laboratory'::text,
  service_id uuid NOT NULL,
  service_category text NOT NULL,
  transaction_type text NOT NULL DEFAULT 'service_request'::text,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  sample_status text NOT NULL DEFAULT 'pending'::text CHECK (sample_status = ANY (ARRAY['pending'::text, 'collected'::text, 'processing'::text, 'analyzed'::text, 'cancelled'::text])),
  result_status text NOT NULL DEFAULT 'pending'::text CHECK (result_status = ANY (ARRAY['pending'::text, 'partial'::text, 'completed'::text, 'cancelled'::text])),
  patient_notes text,
  result_data text,
  result_notes text,
  urgent_flag boolean NOT NULL DEFAULT false,
  completed_by uuid,
  completed_at timestamp with time zone,
  appointment_id uuid,
  payment_status text NOT NULL DEFAULT 'pending_cashier'::text CHECK (payment_status = ANY (ARRAY['pending_cashier'::text, 'paid'::text])),
  receipt_code text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  accession_number text,
  released_by uuid,
  released_at timestamp with time zone,
  tat_minutes integer,
  CONSTRAINT service_requests_pkey PRIMARY KEY (id),
  CONSTRAINT service_requests_clinic_id_fkey FOREIGN KEY (clinic_id) REFERENCES public.clinics(id),
  CONSTRAINT service_requests_requested_by_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id),
  CONSTRAINT service_requests_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.medical_services(id),
  CONSTRAINT service_requests_completed_by_fkey FOREIGN KEY (completed_by) REFERENCES public.profiles(id),
  CONSTRAINT service_requests_appointment_id_fkey FOREIGN KEY (appointment_id) REFERENCES public.appointments(id),
  CONSTRAINT service_requests_released_by_fkey FOREIGN KEY (released_by) REFERENCES public.profiles(id),
  CONSTRAINT service_requests_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text NOT NULL DEFAULT ''::text,
  price numeric NOT NULL DEFAULT 0,
  duration_minutes integer NOT NULL DEFAULT 30,
  specialty_id uuid,
  is_bookable boolean NOT NULL DEFAULT true,
  delivery_mode text NOT NULL DEFAULT 'in_person'::text CHECK (delivery_mode = ANY (ARRAY['in_person'::text, 'teleconsultation'::text, 'hybrid'::text])),
  service_type text NOT NULL DEFAULT 'medical_service'::text CHECK (service_type = ANY (ARRAY['medical_service'::text, 'consultation'::text, 'follow_up'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  medical_service_id uuid,
  CONSTRAINT services_pkey PRIMARY KEY (id),
  CONSTRAINT services_specialty_id_fkey FOREIGN KEY (specialty_id) REFERENCES public.specialties(id),
  CONSTRAINT services_medical_service_id_fkey FOREIGN KEY (medical_service_id) REFERENCES public.medical_services(id)
);
CREATE TABLE public.specialist_appointments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  specialist_id uuid NOT NULL,
  schedule_id uuid,
  referral_id uuid,
  patient_id uuid NOT NULL,
  slot_date date NOT NULL,
  slot_time time without time zone NOT NULL,
  is_booked boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'confirmed'::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT specialist_appointments_pkey PRIMARY KEY (id),
  CONSTRAINT specialist_appointments_specialist_id_fkey FOREIGN KEY (specialist_id) REFERENCES public.doctors(id),
  CONSTRAINT specialist_appointments_schedule_id_fkey FOREIGN KEY (schedule_id) REFERENCES public.specialist_schedules(id),
  CONSTRAINT specialist_appointments_referral_id_fkey FOREIGN KEY (referral_id) REFERENCES public.referrals(id),
  CONSTRAINT specialist_appointments_patient_id_fkey FOREIGN KEY (patient_id) REFERENCES public.patients(id)
);
CREATE TABLE public.specialist_schedules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  specialist_id uuid NOT NULL,
  recurrence jsonb NOT NULL DEFAULT '{}'::jsonb,
  slot_template jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  valid_from date,
  practice_location jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT specialist_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT specialist_schedules_specialist_id_fkey FOREIGN KEY (specialist_id) REFERENCES public.doctors(id)
);
CREATE TABLE public.specialties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  CONSTRAINT specialties_pkey PRIMARY KEY (id)
);
CREATE TABLE public.staff_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL UNIQUE,
  department text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  CONSTRAINT staff_members_pkey PRIMARY KEY (id),
  CONSTRAINT staff_members_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.stock_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL,
  type USER-DEFINED NOT NULL,
  quantity integer NOT NULL,
  remarks text NOT NULL DEFAULT ''::text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT stock_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT stock_transactions_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.inventory_items(id)
);
CREATE TABLE public.suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  contact_person text,
  phone text,
  email text,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  deleted_at timestamp with time zone,
  CONSTRAINT suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.thread_unread (
  thread_id uuid NOT NULL,
  user_id uuid NOT NULL,
  unread_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT thread_unread_pkey PRIMARY KEY (thread_id, user_id),
  CONSTRAINT thread_unread_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.chat_threads(id),
  CONSTRAINT thread_unread_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);